Count,Message,Traceback,Nodes
1,Weird... Cannot call endpoint.,"  File ""/home/ndonij/.local/lib/python3.10/site-packages/locust/user/task.py"", line 343, in run
    self.execute_next_task()
  File ""/home/ndonij/.local/lib/python3.10/site-packages/locust/user/task.py"", line 374, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/home/ndonij/.local/lib/python3.10/site-packages/locust/user/task.py"", line 495, in execute_task
    task(self.user)
  File ""/home/ndonij/Documents/TRAIN_TICKET/TrainTicket/loads/locustfile_stress_booking.py"", line 375, in perform_task
    book(self.client, self.user_id)
  File ""/home/ndonij/Documents/TRAIN_TICKET/TrainTicket/loads/locustfile_stress_booking.py"", line 188, in book
    try_until_success(api_call_ticket)
  File ""/home/ndonij/Documents/TRAIN_TICKET/TrainTicket/loads/locustfile_stress_booking.py"", line 59, in try_until_success
    raise Exception(""Weird... Cannot call endpoint."")
",local
1,Weird... Cannot call endpoint.,"  File ""/home/ndonij/.local/lib/python3.10/site-packages/locust/user/task.py"", line 343, in run
    self.execute_next_task()
  File ""/home/ndonij/.local/lib/python3.10/site-packages/locust/user/task.py"", line 374, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/home/ndonij/.local/lib/python3.10/site-packages/locust/user/task.py"", line 495, in execute_task
    task(self.user)
  File ""/home/ndonij/Documents/TRAIN_TICKET/TrainTicket/loads/locustfile_stress_booking.py"", line 332, in perform_task
    book(self.client, self.user_id)
  File ""/home/ndonij/Documents/TRAIN_TICKET/TrainTicket/loads/locustfile_stress_booking.py"", line 188, in book
    try_until_success(api_call_ticket)
  File ""/home/ndonij/Documents/TRAIN_TICKET/TrainTicket/loads/locustfile_stress_booking.py"", line 59, in try_until_success
    raise Exception(""Weird... Cannot call endpoint."")
",local
